"""The simulation engine: stateless Concordia across cron runs.

Concordia normally holds entity associative memory in-process for a long run.
Our architecture is **ephemeral per tick**: GitHub Actions fires ``advance.py``,
which reconstructs each due scenario from the persisted transcript, advances
exactly the due entity's turn, and persists the result. This module implements
that reconstruction + advance using Concordia's own mechanisms:

* **Entities** are built from the shipped ``basic__Entity`` prefab (the full
  persona component stack: Instructions, Observation, SelfPerception,
  SituationPerception, PersonBySituation, ConcatAct). Entity ``.act()`` IS the
  Concordia persona/memory mechanism — we do not reimplement it.
* **Associative memory** is reconstructed each warm tick by seeding a fresh
  ``AssociativeMemoryBank`` (via the embedder) from the durable transcript:
  persona formative memories + a running summary of earlier turns + the last N
  turns verbatim. This is the idiomatic re-seed path (``bank.add`` uses the
  embedder for retrieval). The window is capped (``MEMORY_WINDOW_TURNS``) to
  stay within the token budget; EVERYTHING remains durable in ``sim_turn_log``.
* **Cold start** seeds formative memories from the persona definitions (the rich
  ``player_specific_context``). When a real Gemini model is present and budget
  allows, the Concordia ``formative_memories_initializer`` Game Master enriches
  them with LLM-generated backstory episodes (the mechanism the brief requires).

To stay within the HARD daily budget, the per-turn advance is intentionally lean:
the entity produces its utterance via Concordia's ``act()``, then ONE structured
model call ("GM resolution") returns the resolved event + trigger + state change
+ the speaker's emotional snapshot as JSON (folding resolution and emotional
extraction into a single call, per the brief). We do NOT run the full multi-call
Sequential generic-GM loop per tick, which would exhaust the budget in hours;
this lean resolution is documented as a deliberate, budget-driven simplification
of the GM loop — it leans on Concordia's persona/memory mechanisms, not a
from-scratch agent loop.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from typing import Any

from concordia.associative_memory import basic_associative_memory
from concordia.prefabs.entity import basic as basic_entity_prefab
from concordia.typing import entity as entity_lib

from sim.emotional_state import parse_resolution, EmotionParseError
from sim.personas import EntityDef, ScenarioDef, BIG_FIVE_FACETS


# ---------------------------------------------------------------------------
# Result of advancing a single turn
# ---------------------------------------------------------------------------


@dataclass
class TurnResult:
    entity_id: str
    utterance: str
    resolution: dict[str, Any]  # {resolved_event, trigger, state_change, emotion_snapshot}
    model_calls_made: int


# ---------------------------------------------------------------------------
# Shared scenario context rendered as seed memories
# ---------------------------------------------------------------------------


_FICTION_NOTICE = (
    "FICTION: This is an entirely fictional simulation generated by language "
    "models. It does not depict real people, institutions, patients, or "
    "clinical/scientific practice."
)
_WARD_ETHICS = (
    "This scenario is a fictional therapeutic-community simulation (Maxwell "
    "Jones tradition). It is strictly process-oriented: it is about how the "
    "community discusses and resolves a shared issue. It does NOT depict acute "
    "symptoms, diagnoses, self-harm, or crisis. Residents are participants with "
    "agency, never clinical objects. If dialogue drifts toward a mental-health "
    "crisis, redirect to the shared community process, do not render it vividly."
)


def shared_scenario_memories(scenario: ScenarioDef) -> list[str]:
    """Render the GM world model + shared problem as shared seed memories."""
    mems = [_FICTION_NOTICE]
    if scenario.ethics_notice:
        mems.append(scenario.ethics_notice)
    if scenario.id == "ward":
        mems.append(_WARD_ETHICS)
    if scenario.environment:
        mems.append(f"Setting: {scenario.environment}")
    if scenario.shared_problem:
        mems.append(f"Shared problem the group is working through: {scenario.shared_problem}")
    return mems


def persona_formative_memories(entity: EntityDef) -> list[str]:
    """Deterministic formative memories derived from the persona definition.

    These ARE the ``player_specific_context`` rendered as memories. They are
    always present (even in dry-run) so the dashboard seeds are exact and tests
    are deterministic. In production the Concordia
    ``formative_memories_initializer`` Game Master can enrich them with
    LLM-generated backstory episodes (see ``cold_start``).
    """
    name = entity.name
    mems: list[str] = []
    mems.append(f"{name}'s role: {entity.role}")
    facets = ", ".join(
        f"{f.capitalize()}={entity.big_five.get(f, '?')}" for f in BIG_FIVE_FACETS
    )
    mems.append(f"{name}'s personality (Big Five): {facets}.")
    if entity.formative_backstory:
        mems.append(f"{name}'s formative backstory: {entity.formative_backstory}")
    if entity.communication_style:
        mems.append(f"{name}'s communication style: {entity.communication_style}")
    if entity.goals:
        mems.append(f"{name}'s goals: {entity.goals}")
    for other, desc in entity.initial_relationships.items():
        mems.append(f"{name}'s relationship with {other}: {desc}")
    mems.append(
        f"{name} begins feeling: mood='{entity.mood}', stress={entity.stress}."
    )
    for other, stance in entity.stances.items():
        mems.append(f"{name}'s starting stance toward {other}: {stance}.")
    return mems


# ---------------------------------------------------------------------------
# Engine
# ---------------------------------------------------------------------------


class ScenarioEngine:
    """Builds entities, reconstructs memory, and advances one turn per call."""

    def __init__(
        self,
        scenario: ScenarioDef,
        model,
        embedder,
        memory_window_turns: int = 20,
    ) -> None:
        self.scenario = scenario
        self.model = model
        self.embedder = embedder
        self.memory_window_turns = memory_window_turns
        self._entity_defs = {e.name: e for e in scenario.entities}

    # -- entity construction + memory reconstruction ------------------------

    def build_entities(
        self,
        formative_memories: dict[str, list[str]],
        recent_turns: list[Any],
        running_summary: str,
    ) -> dict[str, Any]:
        """Reconstruct all 4 entities with capped associative memory.

        Seeds each entity's ``AssociativeMemoryBank`` with shared scenario
        memories, the entity's formative memories, the running summary, and the
        last N turn utterances verbatim. This is the stateless re-seed path.
        """
        shared = shared_scenario_memories(self.scenario)
        recent_texts = [self._turn_to_memory_text(t) for t in recent_turns]
        # Cap the verbatim window.
        window = recent_texts[-self.memory_window_turns :]

        entities: dict[str, Any] = {}
        for name, edef in self._entity_defs.items():
            bank = basic_associative_memory.AssociativeMemoryBank(
                sentence_embedder=self.embedder, allow_duplicates=True
            )
            # Seed shared + formative memories.
            for m in shared:
                bank.add(m)
            for m in formative_memories.get(name, persona_formative_memories(edef)):
                bank.add(m)
            # Running summary of earlier turns (if any).
            if running_summary:
                bank.add(f"Summary of earlier events: {running_summary}")
            # Last N turns verbatim.
            for t in window:
                bank.add(t)

            prefab = basic_entity_prefab.Entity(
                params={"name": name, "goal": self._entity_goal(edef)}
            )
            agent = prefab.build(model=self.model, memory_bank=bank)
            entities[name] = agent
        return entities

    def _entity_goal(self, edef: EntityDef) -> str:
        goal = (
            f"You are {edef.name}, {edef.role}, in a fictional group simulation. "
            "Stay in character and pursue your goals. Speak naturally as yourself "
            "in one or two sentences. Keep it about the shared process."
        )
        if self.scenario.id == "ward":
            goal += " Keep contributions process-oriented; do not dramatize crisis content."
        return goal

    def _turn_to_memory_text(self, turn: Any) -> str:
        """Render a persisted turn as an observation memory for reconstruction."""
        if isinstance(turn, dict):
            eid = turn.get("entity_id", "someone")
            utt = turn.get("utterance", "")
        else:
            eid = getattr(turn, "entity_id", "someone")
            utt = getattr(turn, "utterance", "")
        return f"{eid} said: {utt}"

    # -- advancing a turn ---------------------------------------------------

    def advance_turn(
        self,
        entity_id: str,
        entities: dict[str, Any],
        recent_turns: list[Any],
    ) -> TurnResult:
        """Advance exactly one turn for ``entity_id``.

        1. Observe the most recent prior event to the due entity.
        2. ``entity.act(DEFAULT_ACTION_SPEC)`` (Concordia persona mechanism).
        3. ONE structured "GM resolution" model call -> JSON
           (resolved_event, trigger, state_change, emotion_snapshot).
        """
        calls_before = _model_call_count(self.model)

        agent = entities[entity_id]
        others = [n for n in entities if n != entity_id]

        # Observe the most recent event so it is the freshest context.
        if recent_turns:
            agent.observe(self._turn_to_memory_text(recent_turns[-1]))

        # The entity speaks (Concordia's full component stack runs here).
        raw_action = agent.act(entity_lib.DEFAULT_ACTION_SPEC)
        utterance = _clean_utterance(entity_id, raw_action)

        # One structured resolution call (budget-conserving).
        resolution = self._resolve(entity_id, utterance, others, recent_turns)

        calls_after = _model_call_count(self.model)
        return TurnResult(
            entity_id=entity_id,
            utterance=utterance,
            resolution=resolution,
            model_calls_made=max(0, calls_after - calls_before),
        )

    def _resolve(
        self,
        entity_id: str,
        utterance: str,
        others: list[str],
        recent_turns: list[Any],
    ) -> dict[str, Any]:
        """Single structured model call: event resolution + emotional snapshot."""
        recent_blurbs = []
        for t in recent_turns[-6:]:
            if isinstance(t, dict):
                recent_blurbs.append(f"{t.get('entity_id')}: {t.get('utterance')}")
            else:
                recent_blurbs.append(
                    f"{getattr(t,'entity_id','?')}: {getattr(t,'utterance','')}"
                )
        recent_str = "\n".join(recent_blurbs) or "(no prior turns)"

        prompt = (
            "You are the Game Master resolving one turn in a FICTIONAL group "
            "simulation (no real people/institutions/clinical practice). Given "
            f"the speaker's utterance and context, output ONLY a JSON object.\n\n"
            f"Scenario: {self.scenario.title}.\n"
            f"Shared problem: {self.scenario.shared_problem}\n"
            f"Speaker: {entity_id}. Other participants: {', '.join(others)}.\n\n"
            f"Recent turns:\n{recent_str}\n\n"
            f"{entity_id} just said: \"{utterance}\"\n\n"
            "Return JSON with EXACTLY these keys:\n"
            "{\n"
            '  "resolved_event": "<one sentence: what concretely happened this turn>",\n'
            '  "trigger": "<which prior utterance/event this responds to, or \'opening\'">,\n'
            '  "state_change": {"<other_participant_name>": "<one line if this shifted their stance/mood, else omit them>", ...},\n'
            '  "emotion_snapshot": {\n'
            '    "mood": "<short phrase for the SPEAKER\'s mood now>",\n'
            '    "stress": "<low|medium|high for the SPEAKER>",\n'
            '    "stances": {"<each other participant>": "<one-line stance phrase>"}\n'
            "  }\n"
            "}\n"
            "Output ONLY the JSON object, no prose."
        )
        if self.scenario.id == "ward":
            prompt += (
                "\nKeep the psychiatric-ward scenario strictly process-oriented: "
                "no symptoms/diagnosis/crisis content."
            )

        raw = self.model.sample_text(prompt)
        try:
            return parse_resolution(raw)
        except EmotionParseError:
            # Fall back to a minimal valid resolution so the turn still logs.
            return {
                "resolved_event": utterance,
                "trigger": {"type": "responds_to", "ref": ""},
                "state_change": {},
                "emotion_snapshot": _fallback_snapshot(entity_id, others),
                "_raw_resolution": raw[:500],
            }


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _model_call_count(model) -> int:
    """Best-effort call counter (stub exposes ``call_count``)."""
    return int(getattr(model, "call_count", 0))


def _clean_utterance(entity_id: str, raw: str) -> str:
    """Strip the agent-name prefix Concordia sometimes prepends."""
    text = (raw or "").strip()
    for prefix in (f"{entity_id}:", f"{entity_id} -", f"{entity_id} "):
        if text.startswith(prefix):
            text = text[len(prefix) :].strip()
    if text.lower().startswith(entity_id.lower() + " "):
        text = text[len(entity_id) + 1 :].strip()
    return text or f"{entity_id} pauses, considering the discussion."


def _fallback_snapshot(entity_id: str, others: list[str]) -> dict[str, Any]:
    return {
        "mood": "engaged",
        "stress": "medium",
        "stances": {o: "still reading the room" for o in others},
    }


# ---------------------------------------------------------------------------
# Production cold-start enrichment via the real Concordia initializer GM
# ---------------------------------------------------------------------------


def enrich_formative_via_initializer(
    scenario: ScenarioDef,
    model,
    embedder,
    deterministic_memories: dict[str, list[str]],
) -> dict[str, list[str]]:
    """Use Concordia's ``formative_memories_initializer`` GM to enrich backstories.

    Production-only (needs a real LLM). Runs the initializer once to generate
    LLM backstory episodes from the per-entity ``player_specific_context``,
    then MERGES them with the deterministic persona-derived memories. Any
    failure falls back to the deterministic memories unchanged. This is the
    mechanism the brief requires; it is skipped in dry-run to keep tests
    deterministic and offline.
    """
    try:
        from concordia.prefabs.game_master import formative_memories_initializer as fmi  # noqa: F401
        from concordia.prefabs.simulation.generic import Simulation
        from concordia.typing import prefab as prefab_lib
    except Exception:
        return deterministic_memories

    player_specific_context = {
        e.name: e.persona_context for e in scenario.entities
    }
    player_names = [e.name for e in scenario.entities]

    from concordia.prefabs.entity.basic import Entity as BasicEntity
    from concordia.prefabs.game_master.formative_memories_initializer import (
        GameMaster as InitGameMaster,
    )
    from concordia.prefabs.game_master.generic import GameMaster as GenericGameMaster

    # Build a minimal two-GM config: initializer -> placeholder generic GM.
    try:
        init_prefab = prefab_lib.InstanceConfig(
            prefab="formative_memories_initializer__GameMaster",
            role=prefab_lib.Role.INITIALIZER,
            params={
                "name": "initial setup rules",
                "next_game_master_name": "default rules",
                "shared_memories": shared_scenario_memories(scenario),
                "player_specific_context": player_specific_context,
                "player_specific_memories": {
                    n: deterministic_memories.get(n, []) for n in player_names
                },
            },
        )
        gm_prefab = prefab_lib.InstanceConfig(
            prefab="basic__GameMaster",
            role=prefab_lib.Role.GAME_MASTER,
            params={"name": "default rules"},
        )
        entity_cfgs = [
            prefab_lib.InstanceConfig(
                prefab="basic__Entity",
                role=prefab_lib.Role.ENTITY,
                params={"name": e.name, "goal": ""},
            )
            for e in scenario.entities
        ]
        config = prefab_lib.Config(
            prefabs={
                "basic__Entity": BasicEntity(),
                "formative_memories_initializer__GameMaster": InitGameMaster(),
                "basic__GameMaster": GenericGameMaster(),
            },
            instances=[init_prefab, gm_prefab] + entity_cfgs,
            default_premise="The group convenes to work through their shared problem.",
            default_max_steps=1,
        )
        sim = Simulation(config, model=model, embedder=embedder)
        sim.play(max_steps=1)

        # Harvest generated formative episodes from each entity's memory.
        enriched = {n: list(deterministic_memories.get(n, [])) for n in player_names}
        for ent in sim.get_entities():
            try:
                mem = ent.get_component("__memory__")
                texts = list(mem.get_all_memories_as_text())
                # Only add generated episode-style memories (heuristic).
                for t in texts:
                    if "remembers" in t and t not in enriched[ent.name]:
                        enriched[ent.name].append(t)
            except Exception:
                continue
        return enriched
    except Exception:
        # Any Concordia-internal failure -> keep deterministic memories.
        return deterministic_memories
